# @package _global_

workflow_cls: evorl.algorithms.meta.pbt_sac.param_sac.ParamSACWorkflow

num_envs: 1
normalize_obs: false
rollout_length: 2
discount: 0.99
total_timesteps: 5000000
fold_iters: 8192

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 8192

batch_size: 256
replay_buffer_capacity: 1000000

tau: 0.005
alpha: 0.2 # used as initial alpha value (adaptive_alpha is always true)

actor_update_interval: 2
num_updates_per_iter: 1 # #updates per rollout, usually use: num_envs * rollout_length // actor_update_interval

optimizer:
  lr: 0.0003
  grad_clip_norm: 0 # set 0 or null to turn-off

agent_network:
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]
