# @package _global_

defaults:
  - /agent/meta@target_workflow: paramopenes
  - _self_

workflow_cls: evorl.algorithms.meta.pbt_openes.pbt_param_openes.PBTParamOpenESWorkflow

pop_size: 32

workflow_steps_per_iter: 25

warmup_steps: 100 # warmup_iters = warmup_steps // workflow_steps_per_iter

num_iters: 500

# PBT hyperparameters:
bottom_ratio: 0.2
top_ratio: 0.2

perturb_factor:
  ec_noise_std: 0.2
  ec_lr: 0.2

search_space:
  ec_noise_std:
    low: 0.0001
    high: 1
  ec_lr:
    low: 0.0001
    high: 1

target_workflow:
  num_eval_envs: 16
  eval_episodes: 16

# independent evaluation
num_eval_envs: 128
eval_episodes: 128
eval_interval: 10000000 # default: disable independent evaluation

checkpoint:
  save_interval_steps: 50
