# @package _global_

defaults:
  - /agent/contrib/pop-ep-td3
  - _self_

total_episodes: 20000
random_timesteps: 25600
actor_update_interval: 2 # use default TD3 setting

pop_size: 5
num_learning_offspring: 5

fitness_with_exploration: true
num_envs: 2
episodes_for_fitness: 2 # to match 10*1 episodes in CEMRL
num_rl_updates_per_iter: 4096

num_eval_envs: 128
eval_episodes: 128 # should be divided by num_eval_envs
eval_interval: 10

tags: ["bs2"]
