# @package _global_

defaults:
  - /agent/ppo
  - _self_

num_envs: 32
rollout_length: 16

minibatch_size: 128
reuse_rollout_epochs: 4

total_timesteps: 1000000

eval_interval: 10

optimizer:
  lr: 0.0005
  grad_clip_norm: 1.0

agent_network:
  continuous_action: true
  actor_hidden_layer_sizes: [64, 64]
  critic_hidden_layer_sizes: [64, 64]
