repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.7
    hooks:
      # # Run the linter.
      - id: ruff
        args: [ '--fix' ]
        files: ^evorl/.*\.py$
      # Run the formatter.
      - id: ruff-format
        files: ^evorl/.*\.py$


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        name: "End of file fixer"
      - id: mixed-line-ending
        name: "Mixed line ending fixer"
      - id: check-yaml
        name: "Yaml checker"
        args: [ '--unsafe' ]
        files: ^configs/.*\.ya?ml$
      - id: trailing-whitespace
        name: "Trailing whitespace fixer"
      - id: debug-statements
        name: "Debug imports and breakpoints checker"
      - id: requirements-txt-fixer
        name: "Requirements txt fixer"
        files: requirements/requirements.*\.txt$
