# @package _global_

workflow_cls: evorl.algorithms.contrib.ars_linear.ARSWorkflow

num_iters: 1000

normalize_obs: true # enable of disable VBN
normalize_obs_mode: "RS" # "Global" or "RS" or "VBN"
random_timesteps: 10000 # effective in "Global" and "VBN"

pop_size: 128 # use mirror sampling by default
num_elites: 16 # [1, pop_size//2]

optimizer_name: "sgd"
lr: 0.02
noise_std: 0.03

num_envs: 1
episodes_for_fitness: 1 # episodes per individual for fitness
explore: false
discount: 1.0

num_eval_envs: 128
eval_episodes: 128
eval_interval: 10

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false
  norm_layer_type: "none"
