# @package _global_

workflow_cls: evorl.algorithms.contrib.openes_evox.OpenESWorkflow

pop_size: 128
num_iters: 1000

noise_std: 0.1
optimizer:
  lr: 0.01

num_envs: 16
episodes_for_fitness: 16 # episodes per individual for fitness
mirror_sampling: true
explore: false
discount: 1.0

num_eval_envs: 128
eval_episodes: 128
eval_interval: 10

agent_network:
  actor_hidden_layer_sizes: [16, 16]
  use_bias: true
  norm_layer_type: "none"
