# @package _global_

workflow_cls: evorl.algorithms.contrib.td3_v2.TD3V2Workflow

num_envs: 1
normalize_obs: false
rollout_length: 1
discount: 0.99
total_timesteps: 5000000
fold_iters: 16384

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 16384 # unit: num of iterations

random_timesteps: 25600 # steps filled into the replay buffer
learning_start_timesteps: 25600 # steps before training starts
batch_size: 256
replay_buffer_capacity: 1000000

tau: 0.005 # soft update rate
exploration_epsilon: 0.1
policy_noise: 0.2
clip_policy_noise: 0.5
actor_update_interval: 2
critics_in_actor_loss: first # first or min

optimizer:
  lr: 0.0003
  grad_clip_norm: 0 # set 0 or none to turn-off

agent_network:
  norm_layer_type: "none"
  num_critics: 2
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]

save_replay_buffer: true

checkpoint:
  save_interval_steps: 163840
