# @package _global_

defaults:
  - /agent/erl/erl-openes
  - _self_

total_episodes: 20000

num_rl_agents: 1
warmup_iters: 10 # steps that only learn by EC
num_rl_updates_per_iter: 4096

batch_size: 256
tau: 0.005

pop_size: 32
num_elites: 2
episodes_for_fitness: 1 # must be devided by num_envs
rollout_episodes: 1 # must be devided by num_envs

rl_injection_interval: 1 # replace worst pop agents by rl agents
rl_injection_stepsize: 1.0 # 1: replaced by rl weights, 0: do not inject

agent_network:
  norm_layer_type: "layer_norm"
  num_critics: 2
  critic_hidden_layer_sizes: [256, 256]
  actor_hidden_layer_sizes: [256, 256]
