# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 2000

pop_size: 120
num_elites: 20
lr: 0.015
noise_std: 0.025

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
