# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 500

pop_size: 64
num_elites: 4
lr: 0.02
noise_std: 0.03

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
