# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 1250

pop_size: 16
num_elites: 4
lr: 0.01
noise_std: 0.025

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
