# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 1500

pop_size: 460
num_elites: 230
lr: 0.02
noise_std: 0.0075

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
