# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 2000

pop_size: 2
num_elites: 1
lr: 0.02
noise_std: 0.01

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
