# @package _global_

defaults:
  - /agent/contrib/ars_linear
  - _self_

num_iters: 2500

pop_size: 80
num_elites: 30
lr: 0.03
noise_std: 0.025

agent_network:
  actor_hidden_layer_sizes: []
  use_bias: false


tags: ["ori"]
