# @package _global_

defaults:
  - /agent/contrib/pop-td3
  - _self_

pop_size: 16

num_envs: 1
normalize_obs: false
rollout_length: 2
discount: 0.99
total_timesteps: 80000000 # 5e6*16
fold_iters: 8192

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 8192 # unit: num of iterations

checkpoint:
  save_interval_steps: 81920
