# @package _global_

defaults:
  - /agent/td3
  - _self_

num_envs: 256
normalize_obs: false
rollout_length: 1
discount: 0.99
total_timesteps: 10000000
fold_iters: 128

batch_size: 512

optimizer:
  lr: 0.0006

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 128 # unit: num of iterations

num_updates_per_iter: 32 # each update contains 1 actor update + `actor_update_interval` critic updates

checkpoint:
  save_interval_steps: 1280


tags: ["batch2"]
