# @package _global_

defaults:
  - /agent/exp/ppo/playground/manipulation/manipulation_default
  - _self_

num_envs: 8192
minibatch_size: 10240 # 256 * 40
rollout_length: 40 # 40 * (256 * 32 // 8192)
reuse_rollout_epochs: 4

total_timesteps: 100000000

loss_weights:
  actor_entropy: -0.01

optimizer:
  lr: 0.0003
  grad_clip_norm: 0

agent_network:
  actor_hidden_layer_sizes: [512, 256, 128]
  critic_hidden_layer_sizes: [512, 256, 128]
  policy_obs_key: "state"
  value_obs_key: "privileged_state"
