# @package _global_

defaults:
  - /agent@target_workflow: ppo
  - _self_

workflow_cls: evorl.algorithms.meta.pbt.PBTWorkflow

pop_size: 8

workflow_steps_per_iter: 5

warmup_steps: 5 # warmup_iters = warmup_steps / workflow_steps_per_iter

num_iters: 500

# PBT hyperparameters:
bottom_ratio: 0.2
top_ratio: 0.2

perturb_factor:
  lr: 0.2

search_space:
  lr:
    low: 1e-5
    high: 1e-2

target_workflow:
  num_eval_envs: 16
  eval_episodes: 16

# independent evaluation
num_eval_envs: 128
eval_episodes: 128
eval_interval: 25

checkpoint:
  save_interval_steps: 50
