# @package _global_

defaults:
  - /agent/meta/pbt-paramppo
  - _self_

pop_size: 128

workflow_steps_per_iter: 64 # match the same updates per iter as PBT-SAC(we assume 2critic+1actor sgd updates as one update of SAC)

warmup_steps: 256 # 4 warmup iters

num_iters: 500

checkpoint:
  save_interval_steps: 50
