# @package _global_

defaults:
  - /agent/ec/openes
  - _self_

num_iters: 2000

pop_size: 128

optimizer_name: "adam"
weight_decay: 0.005 # L2 regularization
ec_noise_std:
  init: 0.02
  final: 0.001
  decay: 1.0 # 1.0 means: always use fixed init value
ec_lr:
  init: 0.01
  final: 0.001
  decay: 1.0 # 1.0 means: always use fixed init value

num_envs: 16
episodes_for_fitness: 16 # episodes per individual for fitness
explore: false

agent_network:
  actor_hidden_layer_sizes: [16, 16]
  norm_layer_type: "none"
