# @package _global_

defaults:
  - /agent/exp/ppo/playground/locomotion/locomotion_default
  - _self_

# used for env: "Go1Getup"

total_timesteps: 50_000_000

agent_network:
  actor_hidden_layer_sizes: [512, 256, 128]
  critic_hidden_layer_sizes: [512, 256, 128]
  value_obs_key: "privileged_state"
