# @package _global_

defaults:
  - /agent/ec/nsga2-brax
  - _self_

pop_size: 1024
num_iters: 1000

num_envs: 16
episodes: 16 # episodes per individual for fitness

discount: 1.0
metric_names: ["reward_forward", "reward_ctrl"]


agent_network:
  # actor_hidden_layer_sizes: [] # linear network
  lb: -10.0
  ub: 10.0
  actor_hidden_layer_sizes: [16, 16]
