# @package _global_

defaults:
  - /agent/sac
  - _self_

num_envs: 256
normalize_obs: false
rollout_length: 1
discount: 0.99
total_timesteps: 10000000
fold_iters: 128

adaptive_alpha: true
alpha: 1.0 # used as initial alpha value if adaptive_alpha is true

batch_size: 512

optimizer:
  lr: 0.0006

num_updates_per_iter: 32 # each update contains 1 actor update & actor_update_interval critic updates

num_eval_envs: 16
eval_episodes: 16 # should be divided by num_eval_envs
eval_interval: 128 # unit: num of iterations

checkpoint:
  save_interval_steps: 1280


tags: ["batch2"]
